# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: fsashleydev
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: aws-lambda-serverless-nodee
# "service" is the name of this project. This will also be added to your AWS resource names.
service: aws-lambda-crud-node

provider:
  name: aws
  runtime: nodejs20.x
  lambdaHashingVersion: '20201221'
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Acction:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-west-2:793282269851:table/TaskTable

functions:
  hello:
    handler: src/first.hello
    events:
      - httpApi:
          path: /
          method: get

  createTask:
    handler: src/addTask.addTask
    events:
      - httpApi:
          path: /task
          method: post
  getTasks:
    handler: src/getTasks.getTasks
    events:
      - httpApi:
          path: /tasks
          method: get
  getTask:
    handler: src/getTask.getTask
    events:
      - httpApi:
          path: /task/{id}
          method: get
  updateTask:
    handler: src/updateTask.updateTask
    events:
      - httpApi:
          path: /task/{id}
          method: put
  deleteTask:
    handler: src/deleteTask.deleteTask
    events:
      - httpApi:
          path: /task/{id}
          method: delete

resources:
  Resources:
    TaskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TaskTable
        BillingMode: PAY_PER_REQUEST
        AtributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
